### PR TITLE
HashMap -> TreeMap to preserve Key Order

### LINKED ISSUE #7: Factorization Message Can Be Not In Numerical Order
**Describe the bug**
It seems that the factorization sometimes shows out of numerical order.

Example: `2 * 2 * 11 * 5`

**Expected behavior**
Factorization display is always in numerical order, ie: `2 * 2 * 5 * 11`

factorization ordering

```json
{
  "computationalSteps":[
    {
      "message":"divide 1589 by primes until the remainder is prime",
      "equation":""
    },
    {
      "message":"1589 is not prime",
      "equation":"try 2|1589"
    },
    {
      "message":"1589 is not prime",
      "equation":"try 3|1589"
    },
    {
      "message":"1589 is not prime",
      "equation":"try 5|1589"
    },
    {
      "message":"1589 is not prime",
      "equation":"try 7|1589"
    },
    {
      "message":"7|1589",
      "equation":"1589 = 7⋅227"
    },
    {
      "message":"remainder is prime, stop",
      "equation":""
    }
  ],
  "result":{
    "factors":{
      "227":1,
      "7":1
    },
    "number":1589,
    "message":"∴ 1589 = 227⋅7",
    "resultIsLogicallyTrue":true
  }
}
```

### PR DESCRIPTION
**Pull request by vapurrmaid**
* https://docs.oracle.com/javase/8/docs/api/java/util/TreeMap.html

Fixes #7 

Proposed Changes
- Added Test Case
- Changed `HashMap` to `TreeMap` in `PrimeFactorizationResult`

### CODE REVIEW

File: src/main/java/ca/vapurrmaid/discretemathapplications/domain/computation/PrimeFactorizationResult.java [hunk 1]
```diff
@@ -18,13 +18,13 @@
...
      * of each prime factor.
      *
      * @return prime tally
      */
     @Getter
-    private final Map<Integer, Integer> factors = new HashMap<>();
+    private final Map<Integer, Integer> factors = new TreeMap<>();
 
     @Getter
     private final int number;
```
Comment (vapurrmaid) [inline src/main/java/ca/vapurrmaid/discretemathapplications/domain/computation/PrimeFactorizationResult.java]: 👍

File: src/main/java/ca/vapurrmaid/discretemathapplications/services/PrimeServiceImpl.java [hunk 2]
```diff
@@ -89,7 +89,7 @@ public Computation primeFactorsOfNaturalNumber(NaturalNumber n) {
         int original = n.getNumberAsInteger();
         PrimeFactorizationResult factorization = new PrimeFactorizationResult(original);
 
-        if (n.getNumberAsInteger() == 1) {
+        if (original == 1) {
             factorization.addPrimeFactor(1);
```
Comment (vapurrmaid) [inline src/main/java/ca/vapurrmaid/discretemathapplications/services/PrimeServiceImpl.java]: Good Catch 👍

File: src/test/java/ca/vapurrmaid/discretemathapplications/services/PrimeServiceImplTest.java [hunk 3]
```diff
@@ -70,7 +70,12 @@ public void testPrimeFactorsOfNaturalNumber() throws NaturalNumberException {
         // advanced case - 3 different factors, one repeating, one with multiple digits
         res = primeService.primeFactorsOfNaturalNumber(new NaturalNumber(220)).getResult();
         assertThat(res.getResultIsLogicallyTrue()).isTrue();
-        assertThat(res.getMessage()).isEqualTo("\u2234 220 = 2\u22c52\u22c55\u22c511");
+        assertThat(res.getMessage()).isEqualTo("\u2234 220 = 2\u22c52\u22C55\u22C511");
```
Comment (vapurrmaid) [inline src/test/java/ca/vapurrmaid/discretemathapplications/services/PrimeServiceImplTest.java]: Good Catch - Port these hardcoded math characters to its own module eventually

File: src/test/java/ca/vapurrmaid/discretemathapplications/services/PrimeServiceImplTest.java [hunk 4]
```diff
@@ -70,7 +70,12 @@ public void testPrimeFactorsOfNaturalNumber() throws NaturalNumberException {
...
+
+        // Issue #7 https://github.com/discomath/discomathserver/issues/7 - Test Message Ordering
+        res = primeService.primeFactorsOfNaturalNumber(new NaturalNumber(1589)).getResult();
+        assertThat(res.getResultIsLogicallyTrue()).isTrue();
+        assertThat(res.getMessage()).isEqualTo("\u2234 1589 = 7\u22C5227");
```
Comment (vapurrmaid) [inline src/test/java/ca/vapurrmaid/discretemathapplications/services/PrimeServiceImplTest.java]: 👍

File: src/test/java/ca/vapurrmaid/discretemathapplications/services/PrimeServiceImplTest.java (hunk 3 above)
Comment (vapurrmaid) [reply src/test/java/ca/vapurrmaid/discretemathapplications/services/PrimeServiceImplTest.java]: Adding to Project Board
